### ISSUE TITLE
리뷰 기능을 구현하던중 궁금한점이 생겨 이슈 남겨봅니다.

### ISSUE THREAD

**Issue by SLCube** [SLCube/shop#10]
@kihwankim 

회원이 리뷰를 남기게된다면 리뷰작성자를 같이 저장을 해야되는데 현재 저의 프로젝트엔 spring security와 관련된 설정이 없는 상황입니다.
spring security설정을 먼저하는것이 좋을지 아니면 다른 방법이 있는지 궁금합니다.

**Comment by kihwankim** [comment]
@SLCube 

회원 구현 필수적으로 먼저 진행 -> 나머지 개발을 추천드려요 왜냐하면 회원 데이터를 사용하는 경우가 대다수인데 처음에 회원 정보 없이 개발하다가 나중에 추가하려면 더 힘들 수 있기 때문입니다!
