### ISSUE TITLE
구현중 궁금한것이 있어서 issue남겨봅니다.

### ISSUE THREAD

**Issue by SLCube** [SLCube/shop#21]
1. 지금까지 HelperClass method의 parameter로 repository와 그외 필요한 parameter를 넣어줬는데 [AddressRepositoryHelper](https://github.com/SLCube/shop/blob/4cddfd72e878ad6b018b2407d915231abccf3850/src/main/java/com/slcube/shop/business/address/repository/AddressRepositoryHelper.java#L8-L18)처럼 repository를 주입받는건 어떻게 생각하시나요?

2. [AddressServiceImpl](https://github.com/SLCube/shop/blob/4cddfd72e878ad6b018b2407d915231abccf3850/src/main/java/com/slcube/shop/business/address/service/AddressServiceImpl.java)의 테스트 코드 [AddressServiceTest](https://github.com/SLCube/shop/blob/4cddfd72e878ad6b018b2407d915231abccf3850/src/test/java/com/slcube/shop/business/address/service/AddressServiceTest.java) 작성중 생긴 이슈인데 Address정보를 저장할때 Member에 대한 정보가 저장되지 않아 NotFoundException이 발생합니다. MockUser를 적용할지 아니면 다른 방법이 있을지 조언 부탁드립니다.

**Comment by kihwankim** [comment]
@SLCube 
1번 답변: 편하게 해보셔도되요 저렇게 하는 방법도 있고 다른 방법도 있으니까 편하게 선택해서 하시죠 스타일 차이 라서요!
2번 답변: mock user가 어떤건지 실제 Entity 인지 아닌지 모르겠지만, 저는 User Entity를 repository save method를 통해서 저장해서 처리할거같아요!
