### ISSUE TITLE
브랜치 관리 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by SLCube** [SLCube/shop#24]
Controller를 만들다보니 Service의 변화가 필요해 변경중에 있습니다. 변경하다보니 등록한 issue내용과 실제 작업내용이 달라졌고, 브랜치를 분리해야겠다는 생각이 들었습니다.  

이슈의 단위를 잘못 나눈 제 잘못이지만, 이미 브랜치를 생성하고 작업이 진행중인 상황에서 어떤식으로 브랜치를 분리해야 좋을지 궁금해서 이슈 남겨봅니다.

**Comment by kihwankim** [comment]
그냥 편하게 close 하고 새로 만들든지 아니면 기존의 issue 이름 및 내용 수정 하면좋을거같아요~!

**Comment by SLCube** [comment]
답변 감사합니다.
